config/routes.rb
Bitly::Application.routes.draw do
  root to: 'links#index'
  get '/:link_uid' => 'links#short_link', as: 'short_link'
  resources :links, only: [:create]
end

app/models/link.rb
class Link < ActiveRecord::Base
  before_create :generate_uid
  validate :is_a_url

  default_scope -> { order(count: :desc) }

  def generate_uid
    self.uid = SecureRandom.hex(2) until !self.uid.nil? && Link.where(uid: self.uid).count.zero?
  end

  def is_a_url
    errors.add(:url, 'is not a valid url') unless url =~ /http/
  end
end

app/models/link_dup.rb
class Link < ActiveRecord::Base
  before_create :generate_uid
  validate :is_a_url

  default_scope -> { order(count: :desc) }

  def generate_uid
    self.uid = SecureRandom.hex(2) until !self.uid.nil? && Link.where(uid: self.uid).count.zero?
  end

  def is_a_url
    errors.add(:url, 'is not a valid url') unless url =~ /http/
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @link = Link.new
    @links = Link.all
  end

  def create
    Link.create(link_params)
    redirect_to root_path
  end

  def short_link
    link = Link.find_by(uid: params[:link_uid])
    if link.present?
      link.update(count: link.count + 1)
      redirect_to link.url
    else
      redirect_to root_path
    end
  end

  private

    def link_params
      params.require(:link).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <h1>Links</h1>
  <%= yield %>
</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <%= f.text_field :url, placeholder: 'add link', autofocus: true %>
  <br />
<% end %>

app/views/links/index.html.erb
<%= render 'form' %>

<table class='table table-hover table-striped'>

  <tr>
    <td>URL</td>
    <td>'short' URL</td>
    <td>visits count</td>
  </tr>

  <% @links.each do |link| %>
    <tr>
      <td><%= link.url %></td>
      <td><%= link_to short_link_url(link.uid), short_link_url(link.uid) %></td>
      <td><%= pluralize link.count, 'visit' %></td>
    </tr>
  <% end %>

</table>